# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidlc < Formula
  desc "CLI for managing connections to development lifecycle services"
  homepage "https://github.com/jorgemuza/aidlc-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.3.0/aidlc_0.3.0_darwin_amd64.tar.gz"
      sha256 "9d914c34c21e6bad4f25b6eb986ae76ab75c1cbcac1ce35996f6f8fb1197256c"

      define_method(:install) do
        bin.install "aidlc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.3.0/aidlc_0.3.0_darwin_arm64.tar.gz"
      sha256 "458c675b24d54c087079abc969634c2b06169b30f7151a1e8e3f77b5ce9a5e98"

      define_method(:install) do
        bin.install "aidlc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.3.0/aidlc_0.3.0_linux_amd64.tar.gz"
      sha256 "8d467af7ff9f6d1af1bad689e323c94f1828772608476e8bf66fb582f8b386ed"
      define_method(:install) do
        bin.install "aidlc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.3.0/aidlc_0.3.0_linux_arm64.tar.gz"
      sha256 "ed00774b542e1e367b47988fd6017b85100f5a2fac2fd572c17f7bc31980e87a"
      define_method(:install) do
        bin.install "aidlc"
      end
    end
  end

  test do
    system "#{bin}/aidlc", "version"
  end
end
