# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidlc < Formula
  desc "CLI for managing connections to development lifecycle services"
  homepage "https://github.com/jorgemuza/aidlc-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.2.0/aidlc_0.2.0_darwin_amd64.tar.gz"
      sha256 "ca89d4e3530d81e1a80255ae248e2e33290c7eae8ec20653d5ae56a1f7571bae"

      define_method(:install) do
        bin.install "aidlc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.2.0/aidlc_0.2.0_darwin_arm64.tar.gz"
      sha256 "ee5c9a9abdb4e84a2b3fcf9b862db85b4217e6ba09602dd0232235dc4c7fc9ca"

      define_method(:install) do
        bin.install "aidlc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.2.0/aidlc_0.2.0_linux_amd64.tar.gz"
      sha256 "e7440813b49172781bef11c4e6cf77867b3e62dae63e9d335bd7f85c096e4f5e"
      define_method(:install) do
        bin.install "aidlc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/aidlc-cli/releases/download/v0.2.0/aidlc_0.2.0_linux_arm64.tar.gz"
      sha256 "cc35f31fd328bd1a273434024aaac9e5f5c01e3d1f0fa4dfbbe68d02e725e361"
      define_method(:install) do
        bin.install "aidlc"
      end
    end
  end

  test do
    system "#{bin}/aidlc", "version"
  end
end
