# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docverter < Formula
  desc "Unified document converter — Markdown to DOCX/PDF, Excalidraw to SVG/PNG"
  homepage "https://github.com/jorgemuza/docverter"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.1.0/docverter_0.1.0_darwin_amd64.tar.gz"
      sha256 "006dba2ca5baa40082cbde6772521f3d777b36e4e972f79eae3a169956644b03"

      define_method(:install) do
        bin.install "docverter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.1.0/docverter_0.1.0_darwin_arm64.tar.gz"
      sha256 "09d8a5b1063764e40058c4ece48a6f264a039d4d13feede5c2760be7904c06e6"

      define_method(:install) do
        bin.install "docverter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.1.0/docverter_0.1.0_linux_amd64.tar.gz"
      sha256 "04f337005558c4d1eccec29eeece654d6361339678214f470773e527232fc658"
      define_method(:install) do
        bin.install "docverter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.1.0/docverter_0.1.0_linux_arm64.tar.gz"
      sha256 "c4d9e5ebfc07649fd815efd99ebe74fc961d69da83cd900d5eef7eab880e5382"
      define_method(:install) do
        bin.install "docverter"
      end
    end
  end

  test do
    system "#{bin}/docverter", "version"
  end
end
