# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docverter < Formula
  desc "Unified document converter — Markdown to DOCX/PDF, Excalidraw to SVG/PNG"
  homepage "https://github.com/jorgemuza/docverter"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.2.0/docverter_0.2.0_darwin_amd64.tar.gz"
      sha256 "57a036b097f73601ae21fc5d60cb3b6827277deae1795839eefda2904a544311"

      define_method(:install) do
        bin.install "docverter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.2.0/docverter_0.2.0_darwin_arm64.tar.gz"
      sha256 "8d47c0abc05a8afd4a99f57c28b3c3eee7d011c392c5a2bb8022cad729a94d41"

      define_method(:install) do
        bin.install "docverter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.2.0/docverter_0.2.0_linux_amd64.tar.gz"
      sha256 "ae2e3c690f3fd2c89c2234cf5fa596d62fe4dccc9dc842433c75abac8deeecb5"
      define_method(:install) do
        bin.install "docverter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.2.0/docverter_0.2.0_linux_arm64.tar.gz"
      sha256 "b8ce115be6c89ac678ef0695f4d94bc9459c41aca5c22e893d33efc510c4da3d"
      define_method(:install) do
        bin.install "docverter"
      end
    end
  end

  test do
    system "#{bin}/docverter", "version"
  end
end
