# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docverter < Formula
  desc "Unified document converter — Markdown to DOCX/PDF, Excalidraw to SVG/PNG"
  homepage "https://github.com/jorgemuza/docverter"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.4.0/docverter_0.4.0_darwin_amd64.tar.gz"
      sha256 "b58a2750e7c2ba0842c5037ba6468957798047669e6c68b6a6ceed3139559dd9"

      define_method(:install) do
        bin.install "docverter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.4.0/docverter_0.4.0_darwin_arm64.tar.gz"
      sha256 "bb2a717d4c8873ff218f9be3ac3a786a56516bf088f6e1b4e3f5b59ba91b69d3"

      define_method(:install) do
        bin.install "docverter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.4.0/docverter_0.4.0_linux_amd64.tar.gz"
      sha256 "523d9fc4cbf125282a3adec4830d905f40ff15aee32d8845af2d7278af5e9e4e"
      define_method(:install) do
        bin.install "docverter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/docverter/releases/download/v0.4.0/docverter_0.4.0_linux_arm64.tar.gz"
      sha256 "5065a1fd28c3100f8e3db61cd76e02df4700bbddeb2dd5dfe65fe83f46e282bf"
      define_method(:install) do
        bin.install "docverter"
      end
    end
  end

  test do
    system "#{bin}/docverter", "version"
  end
end
