# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orbit < Formula
  desc "CLI for managing connections to development lifecycle services"
  homepage "https://github.com/jorgemuza/orbit"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.15.0/orbit_0.15.0_darwin_amd64.tar.gz"
      sha256 "539dc43cae4ab3ad33033dba8dbb947990ad6ea2ca631ed8dc0ab03a05d3ab4f"

      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.15.0/orbit_0.15.0_darwin_arm64.tar.gz"
      sha256 "430346f28e58b6041a59c3a395dc0f3af7d8c5374ad681e470ea2b969bf8dad0"

      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.15.0/orbit_0.15.0_linux_amd64.tar.gz"
      sha256 "4bf544121c154beef0257c9f917eb500749624c406be9400669a636feacf78bd"
      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.15.0/orbit_0.15.0_linux_arm64.tar.gz"
      sha256 "58634d9445f5ff5dc66de2f4c7625924c495573091cc3bf64dfb4d76dd4e7c8f"
      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  test do
    system "#{bin}/orbit", "version"
  end
end
