# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orbit < Formula
  desc "CLI for managing connections to development lifecycle services"
  homepage "https://github.com/jorgemuza/orbit"
  version "0.48.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.48.0/orbit_0.48.0_darwin_amd64.tar.gz"
      sha256 "f5f6ecb8d840bcb7a934f460f11bbf101b30c37435a13156669b874529692947"

      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.48.0/orbit_0.48.0_darwin_arm64.tar.gz"
      sha256 "fa36f3466a65987df764771b212891765dd629dc0c6ce6bc9f74ac3bf8614f58"

      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.48.0/orbit_0.48.0_linux_amd64.tar.gz"
      sha256 "8e5d65bdd8d3f18a1a576ce8a8b232535ace4c4502ee5d22173da731286d5667"
      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgemuza/orbit/releases/download/v0.48.0/orbit_0.48.0_linux_arm64.tar.gz"
      sha256 "83d9a5581400496bd379b04de586d172a7e3539ba3d142ace9d4164e930217d4"
      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  test do
    system "#{bin}/orbit", "version"
  end
end
